version: "3"

services:
  react:
    image: node:lts-bullseye
    command: /bin/sh src/run.sh
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    environment:
      HOST_OS: OS
      NODE_ENV: ${NODE_ENV}
      HOST: "0.0.0.0"

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASES} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" 
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
      DATABASE_URL: ${DATABASE_HOSE}
      CHROMEDRIVER_PATH: ${CHROMEDRIVER_PATH}

volumes:
  pgdata:
