version: "3"

services:
  react:
    image: node:lts-bullseye
    command: /bin/sh src/run.sh
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    env_file:
      - ./frontend/.env.development

  db:
    image: postgres
    env_file:
      - ./backend/.env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./backend:/app
      - /Users/brandon/webdriver/chromedriver:/usr/bin/chromedriver
    ports:
      - "8000:8000" 
    depends_on:
      - db
    env_file:
      - ./backend/.env.development

volumes:
  pgdata:
