# Generated by Django 4.2.5 on 2023-09-29 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querier', '0002_joblisting_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querier.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job_listing')},
            },
        ),
        migrations.AddField(
            model_name='joblisting',
            name='interested_users',
            field=models.ManyToManyField(related_name='saved_jobs', through='querier.JobSaved', to=settings.AUTH_USER_MODEL),
        ),
    ]
