# Generated by Django 4.2.5 on 2023-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querier', '0003_jobsaved_joblisting_interested_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
