# Generated by Django 4.2.5 on 2023-09-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.RemoveField(
            model_name='card',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='card',
            name='listing_details',
        ),
        migrations.RemoveField(
            model_name='card',
            name='location',
        ),
        migrations.RemoveField(
            model_name='card',
            name='url',
        ),
    ]
