# Generated by Django 4.2.5 on 2023-09-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querier', '0003_jobsaved_joblisting_interested_users'),
        ('JobNotebook', '0002_remove_card_company_name_remove_card_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='job_listing',
        ),
        migrations.AddField(
            model_name='card',
            name='job_saved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='querier.jobsaved'),
        ),
    ]
