# Generated by Django 4.2.5 on 2023-09-30 00:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobNotebook', '0004_alter_column_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('owner', 'order')},
        ),
    ]
