# Generated by Django 4.2.5 on 2023-09-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotebook', '0005_alter_column_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(),
        ),
    ]
