# Generated by Django 4.2.5 on 2023-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotebook', '0006_alter_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
