# Generated by Django 4.2.5 on 2023-10-09 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotebook', '0007_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
