# Generated by Django 4.2.5 on 2023-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobNotebook', '0008_card_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='company_logo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='listing_details',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
